
-- ======== --
-- PERSONNE --
-- ======== --

CREATE TABLE [dbo].[T_E_PERSONNE_PERS]
(
	[PERS_ID]				INT IDENTITY(1,1),
	[PERS_ARCHIVE_ON]		BIT NOT NULL,
	CONSTRAINT [PK__PERS] PRIMARY KEY CLUSTERED ([PERS_ID])
);

ALTER TABLE [dbo].[T_E_PERSONNE_PERS]
	  ADD CONSTRAINT [DF__PERS_PERS_ARCHIVE_ON] DEFAULT 0 FOR [PERS_ARCHIVE_ON];

-- ================= --
-- PERSONNE PHYSIQUE --
-- ================= --

CREATE TABLE [dbo].[T_E_PERS_PHYSIQUE_PPHY]
(
	[PERS_ID]				INT			NOT NULL,
	[PPHY_NOM_USAGE]		VARCHAR(32) NOT NULL,
	[PPHY_NOM_NAISSANCE]	VARCHAR(32) NOT NULL,
	CONSTRAINT [PK__PPHY] PRIMARY KEY CLUSTERED ([PERS_ID])
);

ALTER TABLE [dbo].[T_E_PERS_PHYSIQUE_PPHY]
	  ADD CONSTRAINT [FK__PPHY_PERS_ID] FOREIGN KEY ([PERS_ID]) 
	  REFERENCES [dbo].[T_E_PERSONNE_PERS] ([PERS_ID]);

-- =============== --
-- PERSONNE MORALE --
-- =============== --

CREATE TABLE [dbo].[T_E_PERS_MORALE_PMOR]
(
	[PERS_ID]				INT			NOT NULL,
	[PMOR_RAISON_SOCIALE]	VARCHAR(80) NOT NULL,
	CONSTRAINT [PK__PMOR] PRIMARY KEY CLUSTERED ([PERS_ID])
);

ALTER TABLE [dbo].[T_E_PERS_MORALE_PMOR]
	  ADD CONSTRAINT [FK__PMOR_PERS_ID] FOREIGN KEY ([PERS_ID]) 
	  REFERENCES [dbo].[T_E_PERSONNE_PERS] ([PERS_ID]);