
CREATE VIEW [dbo].[V_LISTE_TIERS] AS
	SELECT	pers.PERS_ID AS 'PERS_ID',
			CONVERT(BIT, 1) AS 'IS_PERS_PPHY',
			pphy.PPHY_NOM_USAGE AS 'PPHY_NOM_USAGE',
			pphy.PPHY_NOM_NAISSANCE AS 'PPHY_NOM_NAISSANCE',
			pphy.PPHY_PRENOM AS 'PPHY_PRENOM',
			pciv.PCIV_ABREVIATION AS 'PCIV_ABREVIATION',
			pciv.PCIV_LIBELLE AS 'PCIV_LIBELLE',
			NULL AS 'PMOR_RAISON_SOCIALE',
			pers.PERS_ARCHIVE_ON AS 'PERS_ARCHIVE_ON'
	FROM	[dbo].[T_E_PERSONNE_PERS] pers
			INNER JOIN [dbo].[T_E_PERS_PHYSIQUE_PPHY] pphy ON pphy.PERS_ID = pers.PERS_ID
			INNER JOIN [dbo].[T_R_PERS_CIVILITE_PCIV] pciv ON pciv.PCIV_ID = pphy.PCIV_ID

	UNION

	SELECT	pers.PERS_ID AS 'PERS_ID',
			CONVERT(BIT, 0) AS 'IS_PERS_PPHY',
			NULL AS 'PPHY_NOM_USAGE',
			NULL AS 'PPHY_NOM_NAISSANCE',
			NULL AS 'PPHY_PRENOM',
			NULL AS 'PCIV_ABREVIATION',
			NULL AS 'PCIV_LIBELLE',
			pmor.PMOR_RAISON_SOCIALE AS 'PMOR_RAISON_SOCIALE',
			pers.PERS_ARCHIVE_ON AS 'PERS_ARCHIVE_ON'
	FROM	[dbo].[T_E_PERSONNE_PERS] pers
			INNER JOIN [dbo].[T_E_PERS_MORALE_PMOR] pmor ON pmor.PERS_ID = pers.PERS_ID